name: Publish Package

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type to release'
        required: true
        type: choice
        options:
          - Major
          - Minor
          - Patch

run-name: Publish Package ${{ inputs.version_type }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Git
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/geolaborapp'

      - name: Install dependencies
        run: npm install

      - name: Release version
        run: |
          if [ "${{ github.event.inputs.version_type }}" = "Major" ]; then
            npm run release-major
          elif [ "${{ github.event.inputs.version_type }}" = "Minor" ]; then
            npm run release-minor
          else
            npm run release-patch
          fi

      - name: Publish package
        run: git push --follow-tags origin master && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GEOLABOR_GITHUB_TOKEN }}
